analytics: {}
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.709459
  lightness: 0.222972
  rhythmicContrast: 0.635826
  saturation: 0.734234
cta: {}
layout_spectrum: 0.740991
name: pat
opengraph: {}
purpose: {}
typography_spectrum: 0.713406
